# Generated by Django 2.0.2 on 2018-05-26 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotPortfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('averagePrice', models.FloatField(blank=True, null=True)),
                ('marketPrice', models.FloatField(blank=True, null=True)),
                ('profit', models.FloatField(blank=True, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.BotDetail')),
            ],
            options={
                'ordering': ('name', 'symbol'),
            },
        ),
    ]
