# Generated by Django 2.0.2 on 2018-05-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_botportfolio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botaction',
            options={'ordering': ('name', 'symbol', 'date')},
        ),
        migrations.AddField(
            model_name='botaction',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
