# Generated by Django 2.0.2 on 2018-05-30 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_auto_20180530_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botdetail',
            old_name='cash',
            new_name='capital',
        ),
    ]
